package ee.loopalu.garmin.notebook.communication.imagetransfer

import ee.loopalu.garmin.notebook.communication.NotebookCommunicationService
import ee.loopalu.garmin.notebook.image.EncodedImage
import java.util.Base64
import java.util.UUID

/**
 * Contains the two rolling Adler-32 checksum components expected by the watch protocol.
 *
 * @property sumOfByteValues sum of the transferred unsigned byte values,
 * including the initial Adler value.
 * @property cumulativeSum cumulative sum of [sumOfByteValues] after each transferred byte.
 */
data class ImageChecksum(val sumOfByteValues: Int, val cumulativeSum: Int)

/**
 * Describes the complete sequence needed to transfer one encoded image to a watch directory.
 *
 * @property transferId identifier shared by the begin, chunk, and commit requests.
 * @property directoryId identifier of the destination directory on the watch.
 * @property image encoded image metadata, palette, and pixel palette indexes.
 * @property checksum expected checksum of all transferred pixel palette indexes.
 */
data class ImageTransferPlan(
    val transferId: String,
    val directoryId: String,
    val image: EncodedImage,
    val checksum: ImageChecksum
) {
    /** Number of pixel-data chunks required by image transfer. */
    val chunkCount: Int = (image.pixelPaletteIndexes.size + ImageTransferPlanner.CHUNK_SIZE - 1) /
        ImageTransferPlanner.CHUNK_SIZE

    /** Number of acknowledged steps: one begin request, all chunks, and one commit request. */
    val stepCount: Int = chunkCount + 2

    fun getChunkOfPaletteIndexes(index: Int): ByteArray {
        require(index in 0 until chunkCount) {
            "Index is outside the valid chunk range."
        }

        val fromIndex = index * ImageTransferPlanner.CHUNK_SIZE
        val toIndex = minOf(fromIndex + ImageTransferPlanner.CHUNK_SIZE, image.pixelPaletteIndexes.size)
        return image.pixelPaletteIndexes.copyOfRange(fromIndex, toIndex)
    }

    /**
     * Creates the Notebook protocol request for one transfer step.
     *
     * Step zero creates the begin request, steps one through [chunkCount] create chunk requests,
     * and the final step creates the checksum-bearing commit request.
     *
     * @param step zero-based step index in the range from zero to [stepCount] minus one.
     * @return request fields ready to be sent through the Garmin communication client.
     * @throws IllegalArgumentException when [step] is outside the transfer sequence.
     */
    fun createImageTransferRequest(step: Int): Map<String, Any> {
        require(step in 0 until stepCount) {
            "Invalid image transfer step."
        }

        return when {
            step == 0 -> createTransferStartRequest()
            step <= chunkCount -> createChunkRequest(step)
            else -> createTransferCommitRequest()
        }
    }

    private fun createTransferStartRequest(): Map<String, Any> =
        NotebookCommunicationService.beginImageTransferRequest(
            transferId = transferId,
            directoryId = directoryId,
            image = image,
            totalChunks = chunkCount,
            encoding = ImageTransferPlanner.ENCODING
        )

    private fun createTransferCommitRequest(): Map<String, Any> =
        NotebookCommunicationService.commitImageTransferRequest(transferId, checksum)

    private fun createChunkRequest(step: Int): Map<String, Any> =
        NotebookCommunicationService.imageChunkRequest(
            transferId,
            step - 1,
            Base64.getEncoder().encodeToString(getChunkOfPaletteIndexes(step - 1))
        )

    fun calculateImageTransferPercentage(step: Int): Int = ((step + 1) * 100 / stepCount).coerceIn(0, 100)
}

object ImageTransferPlanner {
    const val CHUNK_SIZE = 2_048
    const val ENCODING = "rgb222-index8"
    private const val ADLER_MODULUS = 65_521
    private const val UNSIGNED_BYTE_MASK = 0xFF

    /**
     * Creates a transfer plan for an encoded image and destination directory.
     *
     * @param directoryId identifier of the watch directory that will receive the image.
     * @param encodedImage encoded image whose palette indexes will be chunked and transferred.
     * @param transferId identifier shared by every request in the transfer plan; a UUID is
     * generated by default.
     * @return immutable plan containing transfer metadata and the calculated image checksum.
     * @throws IllegalArgumentException when the image contains no pixel palette indexes.
     */
    fun createTransferPlan(
        directoryId: String,
        encodedImage: EncodedImage,
        transferId: String = UUID.randomUUID().toString()
    ): ImageTransferPlan {
        require(encodedImage.pixelPaletteIndexes.isNotEmpty()) {
            "Image contains no pixel data."
        }

        return ImageTransferPlan(
            transferId = transferId,
            directoryId = directoryId,
            image = encodedImage,
            checksum = getChecksum(encodedImage.pixelPaletteIndexes)
        )
    }

    /**
     * Calculates the two Adler-32 components used by the watch to validate transferred data.
     *
     * Each Kotlin byte is treated as an unsigned value before it is added to the rolling sums.
     *
     * @param bytes complete pixel palette index data in transfer order.
     * @return checksum components that the commit request sends as `checksumA` and `checksumB`.
     */
    fun getChecksum(bytes: ByteArray): ImageChecksum {
        var sumOfByteValues = 1
        var cumulativeSum = 0
        bytes.forEach { byte ->
            val unsignedByte = byte.toInt() and UNSIGNED_BYTE_MASK
            sumOfByteValues = (sumOfByteValues + unsignedByte) % ADLER_MODULUS
            cumulativeSum = (cumulativeSum + sumOfByteValues) % ADLER_MODULUS
        }
        return ImageChecksum(sumOfByteValues, cumulativeSum)
    }
}
